### ISSUE TITLE
无法编译linux平台的so文件

### ISSUE THREAD

**Issue by coolxitech** [futz12/libmatch#2]

**Comment by futz12** [comment]
对Linux的支持尚在TODO LIST中，如果您非要编译linux版本的libmatch，您需要使用相应的ncnn/opencvmoible预编译包替换现有的win32的预编译包。

**Comment by coolxitech** [comment]
> 对Linux的支持尚在TODO LIST中，如果您非要编译linux版本的libmatch，您需要使用相应的ncnn/opencvmoible预编译包替换现有的win32的预编译包。

试了下中文验证码的识别率有点拉胯，想训练个模型不会搞。
